CREATE TABLE `Order`
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  info VARCHAR(256),
  user_id INT,
  datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


CREATE TABLE OrderData
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  order_id INT NOT NULL,
  product_id INT NOT NULL,
  product_count INT NOT NULL
);


CREATE TABLE Product
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  price DECIMAL(10,2)
);

CREATE TABLE User
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  login VARCHAR(128) NOT NULL,
  password VARCHAR(128) NOT NULL,
  isAdmin TINYINT NOT NULL
);
CREATE UNIQUE INDEX unique_login ON User (login);

